try:
    print(x)
except:
    print("something is wrong")
finally:
    print("the try except is finished")
